/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

// @ts-ignore
export default function Model({ glbFile }) {
  const group = useRef();
  // @ts-ignore
  const { nodes } = useGLTF(glbFile || "/hoodie_apose.glb");

  return (
    <group ref={group} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.Scene.children[0].geometry}
        // @ts-ignore
        material={nodes.Scene.children[0].material}
        position={[0, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/hoodie_apose.glb");
