/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model() {
  const group = useRef();
  const { nodes, materials } = useGLTF("/longsleeve_apose.glb");
  return (
    <group ref={group} dispose={null}>
      {console.log(nodes)}
      {console.log(materials)}
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.longsleeve.geometry}
        material={materials.longsleeve}
        position={[0, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/longsleeve_apose.glb");
