/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model() {
  const group = useRef();
  const { nodes, materials } = useGLTF("/tshirt_apose.glb");
  return (
    <group ref={group} dispose={null}>
      {console.log(nodes)}
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.tshirt_apose.geometry}
        material={materials.thsirt}
        position={[0, 0.34, 0]}
      />
    </group>
  );
}

useGLTF.preload("/tshirt_apose.glb");
